name: C/C++ CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: sudo apt install -y libgl libx11-dev libxi-dev libxrandr-dev libglfw3-dev
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make examples
      run: make examples
